name: Dúvida
description: Abra uma solicitação para tirar dúvidas sobre a biblioteca

body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: Detalhe seus pontos de dúvidas em relação a biblioteca.
    validations:
      required: true
